# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [3]:
import torch

Construct a 5x3 matrix, uninitialized:

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[6.6210e-24, 9.5288e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:

In [5]:
x = torch.rand(5, 3) # value range 0-1
print(x)

tensor([[0.1865, 0.8619, 0.2491],
        [0.0791, 0.5425, 0.8883],
        [0.3071, 0.9191, 0.6383],
        [0.4353, 0.3883, 0.3426],
        [0.1571, 0.0018, 0.5897]])


  Construct a matrix filled zeros and of dtype `int64`:

In [6]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [ ]:
x = x.new_ones(5, 3)      # new_* methods take in sizes; inherit data type and device if not specified
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.0515, -0.3035, -1.3155],
        [-0.5790,  0.8535, -0.5706],
        [-2.8349,  0.7860,  0.5895],
        [ 0.1162, -0.5556, -1.2927],
        [-1.0989,  0.9836,  0.2218]])


Get its size:

In [13]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5535,  0.4232, -0.4496],
        [-0.1487,  0.9137, -0.2551],
        [-2.5902,  1.2936,  0.8966],
        [ 0.7682,  0.1249, -0.3434],
        [-0.7407,  1.1531,  0.2722]])


Addition: syntax 2

In [15]:
print(torch.add(x, y))

tensor([[ 0.5535,  0.4232, -0.4496],
        [-0.1487,  0.9137, -0.2551],
        [-2.5902,  1.2936,  0.8966],
        [ 0.7682,  0.1249, -0.3434],
        [-0.7407,  1.1531,  0.2722]])


Addition: providing an output tensor as argument

In [29]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.6030,  0.5141,  0.1003],
        [-0.3872,  1.4181,  1.7018],
        [ 0.3085,  1.0027, -0.9192],
        [ 0.1111, -1.3968, -0.7488],
        [-0.3374,  0.6769, -1.5325]])


Addition: in-place

In [30]:
# adds x to y
y.add_(x)
print(y)

# or
y += x
print(y)

tensor([[-0.6030,  0.5141,  0.1003],
        [-0.3872,  1.4181,  1.7018],
        [ 0.3085,  1.0027, -0.9192],
        [ 0.1111, -1.3968, -0.7488],
        [-0.3374,  0.6769, -1.5325]])
tensor([[-1.3010,  0.8150, -0.5141],
        [-1.5235,  2.1538,  3.2395],
        [ 0.5674,  1.1341, -1.8909],
        [-0.7260, -2.9733, -1.8598],
        [-1.0911,  1.1098, -3.3131]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [31]:
print(x[:, 1])

tensor([ 0.3009,  0.7357,  0.1314, -1.5765,  0.4329])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [32]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [33]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0638])
1.063788652420044


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [34]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [35]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [36]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [37]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [38]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!