# Array Operation

In [1]:
import numpy as np

#### np.reshape()

In [2]:
b = np.arange(8).reshape(4,2); print(b); print()
c = np.reshape(b,(2,4)); print(c)
c = b.reshape((2,4)); print(c) # another written form

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


#### np.flatten()

In [12]:
a = np.arange(8).reshape(2,4); print(a); print()
print(a.flatten())

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3 4 5 6 7]


#### np.transpose()

In [16]:
# np.transpose() exchanges the sequence order of dimensions
a = np.arange(8).reshape(2,4); print(a)
print(a.T) # np.transpose(a) / a.transpose()

a = np.arange(24).reshape(2,3,4); print(a.shape)
print(np.transpose(a, [2,1,0]).shape)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
(2, 3, 4)


(4, 3, 2)

#### np.squeeze() / torch.unsqueeze()

In [18]:
# np.squeeze() reduce the dimensions of "1"
x = np.arange(9).reshape(1,1,3,3); print(x)
y = np.squeeze(x); print(y)
print(y.shape)

[[[[0 1 2]
   [3 4 5]
   [6 7 8]]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [23]:
# numpy has no unsqueeze function, but in torch, there is torch.unsqueeze() for expand the dimension of "1"
import torch 
x = torch.arange(9).reshape(3,3); print(x)
y = torch.unsqueeze(x, 1); print(y.shape) # 1 denotes which dimension to expand

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 1, 3])


#### np.concatenate(arrays, axis)

In [28]:
a = np.array([[1,2],[3,4]]);print(a)
b = np.array([[5,6],[7,8]]);print(b);print()
print(np.concatenate([a,b], axis=0))
print(np.concatenate([a,b], axis=1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### np.stack(arrays, axis)

In [40]:
a = np.array([1,2,3]);print(a)
b = np.array([4,5,6]);print(b)
print("\nstack:")
c = np.stack([a,b],0) # add an extra dim at the "0" dim
print(c)
print(c.shape)

[1 2 3]
[4 5 6]

stack:
[[1 2 3]
 [4 5 6]]
(2, 3)


In [41]:
d = np.stack([a,b],1) # add an extra dim at the "1" dim
print(d) 
print(d.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


### np.where

In [42]:
a = np.eye(10); print(a)
np.where(a == 1) # return two arrays of row indexes and column indexes

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))