# Array
https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

## Define array

#### np.array() & data type

In [27]:
a = np.array([1, 2], dtype=int)
# a = np.array([[1, 2],[3, 4]], dtype=float)
# a = np.array([[1, 2],[3, 4]])
# a = np.array([[1., 2],[3, 4]])
# a = np.array([1, 2], dtype=np.int8)
# a = np.array([1, 2], dtype=np.float32)
print(a, a.dtype, a.shape)

[1 2] int32 (2,)


#### np.empty/zeros/ones/eyes()

In [28]:
x = np.empty([3, 2], dtype=int) # empty array, without any control for initialization
print(x, x.shape)

[[1 2]
 [3 3]
 [4 5]] (3, 2)


In [29]:
y = np.zeros([3, 2]) # zero initialization
print(y, y.shape) 

[[0. 0.]
 [0. 0.]
 [0. 0.]] (3, 2)


In [30]:
z = np.ones([2,3]) # one initialization
print(z, z.shape)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [5]:
t = np.eye(5) # one initialization
print(t, t.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)


#### np.arange() & reshape

In [26]:
a = np.arange(24); print(a)
b = a.reshape(4,6); print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Exercise

In [4]:
# Define an array full of one values whose shape is [3,4,5] and dtype is "float".
np.ones([3,4,5], dtype=float)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])