# Slice & Index

In [3]:
import numpy as np

## Index

In [41]:
a = np.arange(10); print(a)
print(a[4]) # 1-dim index
a = np.arange(10).reshape(2,5); print(a)
print(a[1, 3]) # 2-dim index

print()
print(a[1]) # get the 1-row
print(a[1][3]) # get the 3-element from 1-row

[0 1 2 3 4 5 6 7 8 9]
4
[[0 1 2 3 4]
 [5 6 7 8 9]]
8

[5 6 7 8 9]
8


## Slice
#### [start index : end index : gap], start index is included while end index is not included
Slicing use the same memory with the tensor, the implementation can be seen as recording required indexes.

In [16]:
a = np.arange(10); print(a)
print(a[0:7])
print(a[2:7])
print(a[2:])
print(a[:9])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[2 3 4 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]


In [24]:
a = np.arange(10)
print(a[:])
print(a[2:9:2])
print(a[9:2:-1])
print(a[::-1]) # a reverse method

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[9 8 7 6 5 4 3]
[9 8 7 6 5 4 3 2 1 0]


In [37]:
a = np.arange(10).reshape(2,5); print(a)
print(a[:, :2]) # the first two columns
print()
# slice will not reduce the dimension, but index will
print(a[0, :]) # the first row, 0 is index, the dimension is reduced
print(a[0:1, :]) # the first row, 0:1 is slice, the dimension is reduced

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [5 6]]

[0 1 2 3 4]
[[0 1 2 3 4]]


### boolen Index

In [42]:
x = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]])
print(x>5)
print(x[x > 5]) # boolen index array (same shape with x) to select the elements

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]
