
What is PyTorch?
================
https://pytorch.org/docs/stable/index.html

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


NumPy Bridge
------------
1. Tensors are similar to NumPy’s arrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.  

2. All the Tensors on the CPU except a CharTensor support converting to
NumPy and back. Converting a Torch Tensor to a NumPy array and vice versa is a breeze.  

3. The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

In [3]:
import torch
import numpy as np 

#### GPU available

In [13]:
# Examine your GPUs are available for pytorch (False for CPU version of pytorch)
torch.cuda.is_available()

True

#### array <-> tensor

In [12]:
data = [[1, 2],[3, 4]]
# tensor to array
x_tensor = torch.tensor(data); print(x_tensor)
x_tensor2array = x_tensor.numpy(); print(x_tensor2array); print()
# array to tensor
x_array = np.array(data); print(x_array)
x_array2tenor = torch.from_numpy(x_array); print(x_array2tenor)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


## Define tensor

In [ ]:
data = [[1, 2],[3, 4]]
x = torch.tensor(data); print(x)

In [12]:
# empty/rand/ones/zeros/eye(), xxx_like()
# the difference is you can fill dimensions without brackets at the beginning for these functions
x = torch.empty(2, 3); print(x)
x = torch.rand(2, 3); print(x) # initialization from the Gaussian distribution of N(0,1)
# cuda() means translating your tensors into GPUs
x = torch.zeros(2, 3, dtype=torch.float).cuda(); print(x) # if your device is CPU, please delete the cuda()
y = torch.rand_like(x) # _like means the same shape, data type and device(GPU or CPU)
print(y) 

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5645, 0.0137, 0.1947],
        [0.1591, 0.2213, 0.8251]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
tensor([[0.7100, 0.3382, 0.7818],
        [0.4490, 0.5178, 0.3688]], device='cuda:0')


In [17]:
# get shape
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [7]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2099])
-1.2098873853683472


#### A bunch of operations in numpy have corresponding functions in torch

In [18]:
torch.arange(10)
# torch.stack()
# torch.concatenate()
# torch.squeeze()/unsqueeze()
# torch.flatten()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# permute -> transpose in numpy, to switch the order of dimensions
x = torch.arange(24).reshape(2,3,4)
y = x.permute([2,1,0]); print(y.shape)

torch.Size([4, 3, 2])


## Computation of Tensors
Note: The default calculation is element-wise calculation (+ - * /)

In [6]:
x = torch.arange(6).reshape(2,3); print(x)
y = torch.rand(2, 3)
print(x + y)
print(x*y)
print(x/y)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0.9994, 1.4081, 2.5632],
        [3.0156, 4.7155, 5.0727]])
tensor([[0.0000, 0.4081, 1.1264],
        [0.0469, 2.8618, 0.3636]])
tensor([[  0.0000,   2.4505,   3.5510],
        [191.7046,   5.5909,  68.7556]])


### Matrix Multiplication

In [18]:
# torch.mul() equals "*": Element-wise multiplication
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(torch.mul(a, b).size())
print((a*b).shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [17]:
# torch.mm(): the common mathematical matrix multiplication
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
print(torch.mm(mat1, mat2).size())
print((mat1 @ mat2).shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [19]:
# torch.matmul() equals "@": Matrix product of two tensors, it includes matrix multiplication methods of different dimensions
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](https://pytorch.org/docs/torch).

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [13]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
x = torch.arange(6).reshape(2,3) # x created in CPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    # y.cuda() is also an easy method to move onto the default GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


## Exercise1
Broadcasting is an underlying rules for dealing with unpaired tensors.  
[Broadcasting tutorial](https://deeplearninguniversity.com/pytorch/pytorch-broadcasting/)

## Exercise2
[Pytorch official website](https://pytorch.org/tutorials/) has provided sufficient tutorials for beginners.
Familiarize yourself with PyTorch concepts and modules. Learn how to load data, build deep neural networks, train and save your models in [quickstart guide](https://pytorch.org/tutorials/beginner/basics/intro.html).

We also provide old version of the pytorch tutorials in file folder "old_pytorch_tutorials". The tutorials in [Pytorch official website](https://pytorch.org/tutorials/) is more recommended.
